### ISSUE TITLE
`Failed to load all engine scripts in worker` in NW.js v0.77.0

### ISSUE THREAD

**Issue by Laserwolve** [Laserwolve-Games/DaggerQuest#42]
When exporting DaggerQuest to [NW.js 0.77.0](https://github.com/nwjs/nw.js/releases/tag/nw-v0.77.0) (for Chromium 114), the following error is presented on startup, and the main window stays on a black screen:
```
workermain.js:5 [C3 runtime] Failed to load all engine scripts in worker:  TypeError: Failed to execute 'createObjectURL' on 'URL': Overload resolution failed.
    at LoadScripts (workermain.js:2:258)
    at InitRuntime (workermain.js:5:264)
    at HandleInitRuntimeMessage (workermain.js:1:151)
InitRuntime @ workermain.js:5
```

**Comment by Laserwolve** [comment]
If we change `Use worker` to `No`, we aren't presented with this issue.
